---
name: Main
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make install
      - run: make lint
